### ISSUE TITLE
Assets too large

### ISSUE THREAD

**Issue by ryanm2000** [startupvictoria/startupweek.com.au#1]
The background image of the skyline is massive (amongst others), causing the page to be a ~11mb download. I have optimised the top 3 images for you to use instead. The repo seemed (maybe) out of date so didnt want to update there, I will leave it to whoever is working on the codebase. 

https://dl.dropboxusercontent.com/u/24880508/sv-melb-skyline-bg
https://dl.dropboxusercontent.com/u/24880508/sv-secondround.jpg
https://dl.dropboxusercontent.com/u/24880508/sv-female-founders.jpg

**Comment by lenidot** [comment]
Ryan, 100% agree!
